# Generated by Django 2.2.13 on 2020-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='bvfjghfghfj',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='ghfjghfjhgfj',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hfkhgfhkjhg',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hgfjhgfjh',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='khgfjhgfkhgf',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
