# Generated by Django 2.2.13 on 2020-06-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200615_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='bvfjghfghfj',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='ghfjghfjhgfj',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hfkhgfhkjhg',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='hgfjhgfjh',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='khgfjhgfkhgf',
        ),
    ]
